-- Phase 2.6: Task budget fields
--
-- Adds seven optional financial fields to `tasks` so agencies, consultancies,
-- and internal teams with a cost center can track budgets per task and roll
-- them up at the project level. All fields are nullable USD, no default and
-- no backfill. Teams that don't need budgets leave them empty and pay no
-- UI/DB cost.
--
-- Stored as DOUBLE PRECISION to match `estimated_hours` and keep sqlx decoding
-- consistent with `Option<f64>`. Tech debt: when we introduce a real money
-- type / multi-currency, revisit with NUMERIC(12,2) + rust_decimal.

ALTER TABLE tasks
    ADD COLUMN IF NOT EXISTS rate_per_hour DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS budgeted_hours DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS budgeted_hours_threshold DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS cost_budget DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS cost_budget_threshold DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS cost_per_hour DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS revenue_budget DOUBLE PRECISION;

COMMENT ON COLUMN tasks.rate_per_hour IS 'Billing rate for this task''s work (USD)';
COMMENT ON COLUMN tasks.budgeted_hours IS 'Planned effort for this task';
COMMENT ON COLUMN tasks.budgeted_hours_threshold IS 'Warning threshold for logged-hours overrun';
COMMENT ON COLUMN tasks.cost_budget IS 'Budgeted cost to execute this task (USD)';
COMMENT ON COLUMN tasks.cost_budget_threshold IS 'Warning threshold for cost overrun (USD)';
COMMENT ON COLUMN tasks.cost_per_hour IS 'Internal cost rate for this task (USD)';
COMMENT ON COLUMN tasks.revenue_budget IS 'Expected revenue generated by this task (USD)';
