// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActivityAction = "Created" | "Updated" | "Moved" | "Assigned" | "Unassigned" | "Commented" | "Attached" | "StatusChanged" | "PriorityChanged" | "Deleted";
