// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../../../crates/db/bindings/serde_json/JsonValue";

export type ColumnBroadcast = { id: string, name: string, position: string, color: string | null, status_mapping: JsonValue | null, };
