// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskPriority } from "./TaskPriority";

export type TaskBroadcast = { id: string, title: string, priority: TaskPriority, column_id: string, position: string, assignee_ids: Array<string>, watcher_ids: Array<string>, updated_at: string, changed_fields: Array<string> | null, origin_user_name: string | null, };
