//! HTML → PDF conversion via headless Chrome and WAHA delivery
//!
//! PDFs are generated by rendering HTML through headless Chrome,
//! then served via the frontend container and sent to WAHA as a URL.

use std::path::Path;
use tokio::process::Command;

use crate::notifications::whatsapp::{WahaClient, WhatsAppError};

#[derive(Debug, thiserror::Error)]
pub enum PdfError {
    #[error("Failed to write HTML temp file: {0}")]
    Io(#[from] std::io::Error),
    #[error("Chrome PDF generation failed: {0}")]
    Chrome(String),
    #[error("WhatsApp send failed: {0}")]
    WhatsApp(#[from] WhatsAppError),
    #[error("PDF file not found after generation")]
    PdfNotFound,
    #[error("Docker copy failed: {0}")]
    DockerCopy(String),
}

/// Generate a PDF from HTML using headless Chrome.
/// Returns the PDF file bytes.
pub async fn generate_pdf_from_html(html: &str) -> Result<Vec<u8>, PdfError> {
    let tmp_dir = std::env::temp_dir();
    let html_path = tmp_dir.join(format!("report_{}.html", uuid::Uuid::new_v4()));
    let pdf_path = tmp_dir.join(format!("report_{}.pdf", uuid::Uuid::new_v4()));

    // Write HTML to temp file
    tokio::fs::write(&html_path, html).await?;

    // Run headless Chrome
    let output = Command::new("google-chrome")
        .args([
            "--headless",
            "--disable-gpu",
            "--no-sandbox",
            "--disable-software-rasterizer",
            "--run-all-compositor-stages-before-draw",
            "--print-to-pdf-no-header",
            &format!("--print-to-pdf={}", pdf_path.display()),
            &format!("file://{}", html_path.display()),
        ])
        .output()
        .await?;

    // Cleanup HTML
    let _ = tokio::fs::remove_file(&html_path).await;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        if !Path::new(&pdf_path).exists() {
            return Err(PdfError::Chrome(stderr.to_string()));
        }
    }

    if !Path::new(&pdf_path).exists() {
        return Err(PdfError::PdfNotFound);
    }

    let pdf_bytes = tokio::fs::read(&pdf_path).await?;
    let _ = tokio::fs::remove_file(&pdf_path).await;

    Ok(pdf_bytes)
}

/// Generate PDF, host it via the frontend container, and send the URL via WAHA.
///
/// Flow: HTML → Chrome → PDF → docker cp to frontend → WAHA sendFile with URL
pub async fn generate_and_send_pdf(
    waha_client: &WahaClient,
    phone_number: &str,
    html: &str,
    filename: &str,
    caption: Option<&str>,
    app_url: &str,
) -> Result<(), PdfError> {
    let pdf_bytes = generate_pdf_from_html(html).await?;

    // Write PDF to temp location
    let tmp_pdf = std::env::temp_dir().join(filename);
    tokio::fs::write(&tmp_pdf, &pdf_bytes).await?;

    // Copy into the frontend container's nginx html dir
    let docker_output = Command::new("docker")
        .args([
            "cp",
            &tmp_pdf.display().to_string(),
            &format!("taskbolt-frontend:/usr/share/nginx/html/{}", filename),
        ])
        .output()
        .await?;

    let _ = tokio::fs::remove_file(&tmp_pdf).await;

    if !docker_output.status.success() {
        let stderr = String::from_utf8_lossy(&docker_output.stderr);
        return Err(PdfError::DockerCopy(stderr.to_string()));
    }

    // Send via WAHA using public URL
    let pdf_url = format!("{}/{}", app_url.trim_end_matches('/'), filename);

    waha_client
        .send_file_url(phone_number, &pdf_url, filename, "application/pdf", caption)
        .await?;

    // Schedule cleanup after 60s (fire-and-forget)
    let fname = filename.to_string();
    tokio::spawn(async move {
        tokio::time::sleep(std::time::Duration::from_secs(60)).await;
        let _ = Command::new("docker")
            .args([
                "exec",
                "taskbolt-frontend",
                "rm",
                "-f",
                &format!("/usr/share/nginx/html/{}", fname),
            ])
            .output()
            .await;
    });

    Ok(())
}
