// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ColumnBroadcast = { id: string, name: string, position: string, color: string, status_type: string, };
