// This file will contain types generated by ts-rs from the Rust backend
// The types will be auto-generated and placed here during the build process

// Re-export common types for convenience
export * from '../../core/services/auth.service';
export * from '../../core/services/workspace.service';
export * from '../../core/services/board.service';
export * from '../../core/services/task.service';
export * from '../../core/services/notification.service';
export * from '../../core/services/profile.service';
export * from '../../core/services/comment.service';
export * from '../../core/services/activity.service';
export * from '../../core/services/attachment.service';
export * from '../../core/services/team.service';
export * from '../../core/services/my-tasks.service';
export * from '../../core/services/admin.service';
