// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecurrencePattern = "daily" | "weekly" | "biweekly" | "monthly" | "custom" | "yearly" | "weekdays" | "custom_weekly";
