export type LightTheme =
  | 'white-heaven'
  | 'sea-foam'
  | 'warm-earth'
  | 'storm-cloud'
  | 'morning-sky'
  | 'misty-forest'
  | 'modern-dental'
  | 'cosmic'
  | 'mindful'
  | 'purple-scale'
  | 'pastel-rose'
  | 'french-blues'
  | 'sunset-website'
  | 'terracotta-studio'
  | 'electric-teal'
  | 'signal-blue'
  | 'hot-rose';

export type DarkTheme =
  | 'warm-earth-dark'
  | 'purple-night'
  | 'cherry-blossom'
  | 'sunset-dusk'
  | 'purple-haze'
  | 'ocean-deep'
  | 'luna'
  | 'coffee'
  | 'moon'
  | 'wine'
  | 'gold-crimson'
  | 'pink-gray'
  | 'yellow-dark'
  | 'forest-night'
  | 'bloodstone'
  | 'red-noir'
  | 'terracotta-studio-dark'
  | 'neon-mint';

export type ColorMode = 'light' | 'dark' | 'system';
