pub mod auth;
pub mod invitation;
pub mod task;
pub mod workspace;
pub mod board;
pub mod column;
pub mod comments;
pub mod activity_log;
pub mod attachment;
pub mod notification;
pub mod notification_preferences;
pub mod cron;
pub mod onboarding;
pub mod team_overview;
pub mod my_tasks;
pub mod health;
pub mod admin_audit;
pub mod admin_users;
pub mod admin_trash;

pub use auth::auth_router;
pub use invitation::invitation_router;
pub use task::task_router;
pub use workspace::workspace_router;
pub use board::{board_router, workspace_boards_router};
pub use column::{board_columns_router, column_router};
pub use comments::comment_router;
pub use activity_log::activity_log_router;
pub use attachment::attachment_router;
pub use notification::notification_router;
pub use notification_preferences::notification_preferences_router;
pub use cron::cron_router;
pub use onboarding::onboarding_router;
pub use team_overview::team_overview_router;
pub use my_tasks::my_tasks_router;
pub use health::{health_handler, liveness_handler, readiness_handler};
pub use admin_audit::admin_audit_router;
pub use admin_users::admin_users_router;
pub use admin_trash::admin_trash_router;
